### ISSUE TITLE
Direction of linking

### ISSUE THREAD

**Issue by lode** [jelhan/json-api-bulk-create-extension#1]
I don't understand the direction of linking described in this specification.

The words state included resources should point to primary data resources. However the example json shows a primary data resource linking to an included resource.

I don't know which of these is intended. But I would prefer primary data resources pointing to included resources. I don't really understand the use case where the other way around would be useful. Plus I think it would help a lot of the linking is the same as in compound documents for others to easily adopt this extension.

**Comment by lode** [comment]
I re-read this part a few times more and think I understand a bit better now.

It is this sentence that confuses me (emphasis mine):

> Note: This is similar to the "full linkage" requirement as defined for [compound documents](https://jsonapi.org/format/#document-compound-documents) by the JSON:API specification itself. But the direction of the graph is reversed. In a compound document every included resource must be referenced by a primary resource. This extension **requires that every included resource references a primary resource**.

If I understand correctly, this is _not_ true / not that absolute. It is only required _if_ the included resource is actually pointing to another resource. But if an included resource only has attributes and no relationships, there is no linking to elsewhere.

Or does this mean that the included resource 'references' another resource via its own `lid`? Then I think the word 'references' confuses me. Does it mean 'uses an lid that is referred to by a primary resource'?

**Comment by jelhan** [comment]
> However the example json shows a primary data resource linking to an included resource.

The example is wrong. Good catch. Will fix it asap.

> I don't know which of these is intended. But I would prefer primary data resources pointing to included resources.

The opposite is intended. A resource can only point to another resource in its relationship linkage, which 1) exists before or 2) is listed previously in the document. The intent is to allow streaming: An API does not need to know about resources listed later in the document to process a resource.

**Comment by jelhan** [comment]
I created #6 to fix the wrong example.
